// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17udz5b-SJzHj8zi0MYf01ysz8xz4DtE',
    appId: '1:557036727338:web:be13e558d2d3994ea6a753',
    messagingSenderId: '557036727338',
    projectId: 'tester-8f808',
    authDomain: 'tester-8f808.firebaseapp.com',
    storageBucket: 'tester-8f808.firebasestorage.app',
    measurementId: 'G-WD3NLGML8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGwu0abMo9-nPsTeQAMi5mhgfjRVGkfjE',
    appId: '1:557036727338:android:c8e32c63e45c85a3a6a753',
    messagingSenderId: '557036727338',
    projectId: 'tester-8f808',
    storageBucket: 'tester-8f808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXnoy5qQsKnqp8kkjtacdbM3TRa1KrIs',
    appId: '1:557036727338:ios:7b329855793862fda6a753',
    messagingSenderId: '557036727338',
    projectId: 'tester-8f808',
    storageBucket: 'tester-8f808.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXnoy5qQsKnqp8kkjtacdbM3TRa1KrIs',
    appId: '1:557036727338:ios:7b329855793862fda6a753',
    messagingSenderId: '557036727338',
    projectId: 'tester-8f808',
    storageBucket: 'tester-8f808.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD17udz5b-SJzHj8zi0MYf01ysz8xz4DtE',
    appId: '1:557036727338:web:61eab4bbdf3ad8c3a6a753',
    messagingSenderId: '557036727338',
    projectId: 'tester-8f808',
    authDomain: 'tester-8f808.firebaseapp.com',
    storageBucket: 'tester-8f808.firebasestorage.app',
    measurementId: 'G-ETWH2MMEEC',
  );
}
